# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
   
    - name: Build solution
      run: dotnet build -c Release
    
    - name: Install NUnit.ConsoleRunner
      run: nuget install xunit.runner.console -Version 2.9.2 -DirectDownload -OutputDirectory .

    - name: Install OpenCover
      run: nuget install OpenCover -Version 4.7.1221 -DirectDownload -OutputDirectory .

    - name: Run UnitTests and coverage
      run: .\opencover.4.7.1221\tools\OpenCover.Console.exe -register:user -target:".\NUnit.ConsoleRunner.3.13.0\tools\nunit3-console.exe" -targetargs:"D:\a\VoronoiGrid\VoronoiGrid\VoronoiTests\bin\Release\VoronoiTests.dll" -filter:"+[VoronoiEngine*]* -[VoronoiTests*]*" -output:".\VoronoiEngine_coverage.xml"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
