# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
   
    - name: Build solution
      run: dotnet build -c Release
    
    - name: Install OpenCover
      run: nuget install OpenCover -Version 4.7.1221 -DirectDownload -OutputDirectory .

    - name: Run UnitTests and coverage
      run: dotnet test VoronoiTests/VoronoiTests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
